version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8437:8437"
    depends_on:
      - cloudsql-proxy
    environment:
      - DB_HOST=cloudsql-proxy
      - DB_PORT=5432
      - DB_USER=execute
      - DB_PASSWORD=execute
      - DB_NAME=execute_db
      - DB_SSLMODE=disable
    restart: on-failure
    networks:
      - back-end

  web:
    build: ./web
    ports:
      - "5173:5173"
    restart: on-failure
    networks:
      - front-end
      - back-end

  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.15.2
    ports:
      - "5432:5432"
    volumes:
      - ./credentials.json:/credentials.json
    command: --address=0.0.0.0 --port=5432 --credentials-file /credentials.json pure-wall-459114-v4:europe-central2:execute-db
    restart: always
    networks:
      - back-end

networks:
  front-end:
  back-end: