apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: staging
  labels:
    app: server
spec:
  containers:
    - name: server
      image: europe-central2-docker.pkg.dev/pure-wall-459114-v4/docker-repo/server:latest
      ports:
        - containerPort: 8437
      env:
        - name: DB_HOST
          value: "cloudsql-proxy"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "execute"
        - name: DB_PASSWORD
          value: "execute"
        - name: DB_NAME
          value: "execute_db"
        - name: DB_SSLMODE
          value: "disable"
