apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: staging
  labels:
    app: server
spec:
  serviceAccountName: server-sa
  containers:
    - name: server
      image: europe-central2-docker.pkg.dev/pure-wall-459114-v4/docker-repo/server:latest
      ports:
        - containerPort: 8437
      env:
        - name: DB_HOST
          value: "cloudsql-proxy"
        - name: DB_PORT
          value: "5432"
        - name: DB_SSLMODE
          value: "disable"
        - name: GCP_PROJECT_ID
          value: "pure-wall-459114-v4"
        - name: PUBSUB_TOPIC_NAME
          value: "execute-pubsubtobq"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: server-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: server-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: server-secrets
              key: DB_NAME
